FROM mcr.microsoft.com/dotnet/sdk:3.1
ENV ASPNETCORE_ENVIRONMENT=development
ENV DOTNET_ENVIRONMENT=development
#install debugger for NET Core
RUN apt-get update
RUN apt-get install -y unzip
RUN curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l ~/vsdbg

WORKDIR /app
# Copy csproj and restore as distinct layers
COPY ReactApp.sln ./

COPY Application ./Application
COPY Domain ./Domain
COPY Infrastructure ./Infrastructure
COPY Persistence ./Persistence
COPY API ./API
COPY data ./data

RUN dotnet restore
WORKDIR /app/API

ENTRYPOINT ["dotnet", "watch", "run", "environment=development"]

# # Copy everything else and build
# RUN dotnet publish -c Debug -o /out
# FROM mcr.microsoft.com/dotnet/aspnet:3.1 as final
# WORKDIR /app
# COPY --from=build /out ./
# WORKDIR /app

# ENTRYPOINT ["dotnet", "API.dll"]
