version: "3.2"
networks:
  frontend:
services:
  db:
    image: mysql
    container_name: activitydb
    networks:
      - frontend
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql
      - ./database_dump.sql:/docker-entrypoint-initdb.d/database_dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: example
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: reactapp_image
    container_name: reactapp_container
    volumes:
      - type: bind
        source: ./
        target: /app
    networks:
      - frontend
    ports: 
      - "5000:5000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
