version: "3.2"

services:
  db:
    image: mysql
    container_name: activitydb
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql
      - ./database_dump.sql:/docker-entrypoint-initdb.d/database_dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: example