version: "3.1"
networks:
  frontend:
services:
  db:
    image: mysql
    container_name: activitydb
    networks:
      - frontend
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - .\database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql
      - .\database_dump.sql:/docker-entrypoint-initdb.d/database_dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: example
  app:
    build: .
    container_name: reactapp
    networks:
      - frontend
    ports: 
      - "5000:5000"
