version: "3.1"
networks:
  frontend:
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.database
    container_name: activitydb
    networks:
      - frontend
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    container_name: reactapp_container
    networks:
      - frontend
    ports: 
      - "5000:5000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t