version: "3.1"
networks:
  frontend:
services:
  activitydb:
    build:
      context: ./../..
      dockerfile: ./deployment/prod/Dockerfile.prod.database
    container_name: activitydb
    ports:
      - "3306:3306"
    networks:
      - frontend

  backend:
    build:
      context: ./../..
      dockerfile: ./deployment/prod/Dockerfile.prod.backend
    container_name: activitybackend_container
    # ports:
    #   - "5000:5000"
    networks:
      - frontend
    stdin_open: true # docker run -i
    tty: true # docker run -t

  frontend:
    build:
      context: ./../..
      dockerfile: ./deployment/prod/Dockerfile.prod.frontend
    container_name: activityfrontend_container
    ports:
      - "80:80"
    networks:
      - frontend
    volumes: 
      - ./nginx_local.conf:/etc/nginx/conf.d/default.conf