**/.git
**/.devcontainer
**/.github
**/.vs
**/.vscode
**/.github

**/node_modules
**/build
**/.next
**/cypress

**/API
**/Application
**/Domain
**/Infrastructure
**/Persistence

**/docker-compose*
**/Dockerfile*
