**/.git
**/.devcontainer
**/.github
**/.vs
**/.vscode
**/.github

**/node_modules
**/build
**/package.json
**/package-lock.json
**/.next

**/API
**/Application
**/Domain
**/Infrastructure
**/Persistence

**/docker-compose*
**/Dockerfile*
