FROM cypress/base as node_cache
WORKDIR /cache/
COPY ./client-app/package.json .
RUN npm install --verbose

FROM cypress/browsers:node14.17.0-chrome88-ff89
WORKDIR /e2e/client-app
COPY --from=node_cache /root/.cache/Cypress /root/.cache/Cypress
COPY --from=node_cache /cache/ .
RUN npx cypress verify