name: e2e2
on:
  push:
    branches:
      - master

jobs:
  HomeTest:
    runs-on: ubuntu-20.04
    steps:
      # - name: uncommend this on github
      #   run: apt update && apt install docker-compose -y
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: build images
        run: docker-compose -f deployment/test/docker-compose-cypress.yml build

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Run home tests
        run: |
          export TEST=home && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress

  CreateNewTest:
    runs-on: ubuntu-20.04
    steps:
      # - name: uncommend this on github
      #   run: apt update && apt install docker-compose -y
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: build images
        run: docker-compose -f deployment/test/docker-compose-cypress.yml build

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Run activities tests
        run: |
          export TEST=activities && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress

  ActivityTest:
    runs-on: ubuntu-20.04
    steps:
      # - name: uncommend this on github
      #   run: apt update && apt install docker-compose -y
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: build images
        run: docker-compose -f deployment/test/docker-compose-cypress.yml build

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Run create activity tests
        run: |
          export TEST=createactivity && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress

  ActivitiesTest:
    runs-on: ubuntu-20.04
    steps:
      # - name: uncommend this on github
      #   run: apt update && apt install docker-compose -y
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: build images
        run: docker-compose -f deployment/test/docker-compose-cypress.yml build

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Run activity tests
        run: |
          export TEST=activity && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress

  ManageTest:
    runs-on: ubuntu-20.04
    steps:
      # - name: uncommend this on github
      #   run: apt update && apt install docker-compose -y
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: build images
        run: docker-compose -f deployment/test/docker-compose-cypress.yml build

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Run manage tests
        run: |
          export TEST=manage && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress

  ProfileTest:
    runs-on: ubuntu-20.04
    steps:
      # - name: uncommend this on github
      #   run: apt update && apt install docker-compose -y
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: build images
        run: docker-compose -f deployment/test/docker-compose-cypress.yml build

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Run profile tests
        run: |
          export TEST=profile && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress

  AuthTest:
    runs-on: ubuntu-20.04
    steps:
      # - name: uncommend this on github
      #   run: apt update && apt install docker-compose -y
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: build images
        run: docker-compose -f deployment/test/docker-compose-cypress.yml build

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Run auth tests
        run: |
          export TEST=auth && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress
