name: e2e
on:
  push:
    branches:
      - master

jobs:
  dockerbuild:
    runs-on: ubuntu-20.04
    env:
      TEST: profile
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Pull base image from DigitalOcean Container Registry
        run: docker pull registry.digitalocean.com/imagerepo/activity:activityfrontendbase-latest

      # - name: uncommend this on github
      #   run: apt update && apt install docker-compose -y
      - name: build images
        run: docker-compose -f deployment/test/docker-compose-cypress.yml build
      - name: save images
        run: mkdir /root/artifacts && docker save test_cypress  > cypress.tar
      - name: upload image
        uses: actions/upload-artifact@v2
        with:
          name: cypress
          path: cypress.tar
          retention-days: 1
  # dockerrun:
  #   runs-on: ubuntu-20.04
  #   needs: dockerbuild
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Download artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: cypress
  #         path: /path/to/artifacts

  #     - name: Run auth tests
  #       run: |
  #         export TEST=auth && \
  #         docker-compose -f deployment/test/docker-compose-cypress.yml up \
  #          --abort-on-container-exit --exit-code-from cypress
      # - name: Run profile tests
      #   run: |
      #     export TEST=profile && \
      #     docker-compose -f deployment/test/docker-compose-cypress.yml up \
      #      --abort-on-container-exit --exit-code-from cypress

      # - name: Run manage tests
      #   run: |
      #     export TEST=manage && \
      #     docker-compose -f deployment/test/docker-compose-cypress.yml up \
      #      --abort-on-container-exit --exit-code-from cypress

      # - name: Run activities tests
      #   run: |
      #     export TEST=activities && \
      #     docker-compose -f deployment/test/docker-compose-cypress.yml up \
      #      --abort-on-container-exit --exit-code-from cypress

      # - name: Run activity tests
      #   run: |
      #     export TEST=activity && \
      #     docker-compose -f deployment/test/docker-compose-cypress.yml up \
      #      --abort-on-container-exit --exit-code-from cypress

      # - name: Run home tests
      #   run: |
      #     export TEST=home && \
      #     docker-compose -f deployment/test/docker-compose-cypress.yml up \
      #      --abort-on-container-exit --exit-code-from cypress

      # - name: Run create activity tests
      #   run: |
      #     export TEST=createactivity && \
      #     docker-compose -f deployment/test/docker-compose-cypress.yml up \
      #      --abort-on-container-exit --exit-code-from cypress
