name: e2e2
on:
  push:
    branches:
      - master

jobs:
  HomeTest:
    runs-on: ubuntu-20.04
    steps:
      # - name: uncommend this on github
      #   run: apt update && apt install docker-compose -y
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: build images
        run: docker-compose -f deployment/test/docker-compose-cypress.yml build

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Run home tests on chrome
        run: |
          export TEST=home BROWSER=chrome && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress

      - name: Run home tests on firefox
        run: |
          export TEST=home BROWSER=firefox && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress

  CreateNewTest:
    runs-on: ubuntu-20.04
    steps:
      # - name: uncommend this on github
      #   run: apt update && apt install docker-compose -y
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: build images
        run: docker-compose -f deployment/test/docker-compose-cypress.yml build

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Run activities tests chrome
        run: |
          export TEST=activities BROWSER=chrome && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress

      - name: Run activities tests firefox
        run: |
          export TEST=activities BROWSER=firefox && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress

  ActivityTest:
    runs-on: ubuntu-20.04
    steps:
      # - name: uncommend this on github
      #   run: apt update && apt install docker-compose -y
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: build images
        run: docker-compose -f deployment/test/docker-compose-cypress.yml build

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Run create activity tests chrome
        run: |
          export TEST=createactivity BROWSER=chrome && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress

      - name: Run create activity tests firefox
        run: |
          export TEST=createactivity BROWSER=firefox && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress

  ActivitiesTest:
    runs-on: ubuntu-20.04
    steps:
      # - name: uncommend this on github
      #   run: apt update && apt install docker-compose -y
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: build images
        run: docker-compose -f deployment/test/docker-compose-cypress.yml build

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Run activity tests chrome
        run: |
          export TEST=activity BROWSER=chrome && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress

      - name: Run activity tests firefox
        run: |
          export TEST=activity BROWSER=firefox && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress

  ManageTest:
    runs-on: ubuntu-20.04
    steps:
      # - name: uncommend this on github
      #   run: apt update && apt install docker-compose -y
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: build images
        run: docker-compose -f deployment/test/docker-compose-cypress.yml build

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Run manage tests chrome
        run: |
          export TEST=manage BROWSER=chrome && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress

      - name: Run manage tests firefox
        run: |
          export TEST=manage BROWSER=firefox && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress

  ProfileTest:
    runs-on: ubuntu-20.04
    steps:
      # - name: uncommend this on github
      #   run: apt update && apt install docker-compose -y
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: build images
        run: docker-compose -f deployment/test/docker-compose-cypress.yml build

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Run profile tests chrome
        run: |
          export TEST=profile BROWSER=chrome && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress

      - name: Run profile tests firefox
        run: |
          export TEST=profile BROWSER=firefox && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress

  AuthTest:
    runs-on: ubuntu-20.04
    steps:
      # - name: uncommend this on github
      #   run: apt update && apt install docker-compose -y
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: build images
        run: docker-compose -f deployment/test/docker-compose-cypress.yml build

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Run auth tests chrome
        run: |
          export TEST=auth BROWSER=chrome && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress

      - name: Run auth tests firefox
        run: |
          export TEST=auth BROWSER=firefox && \
          docker-compose -f deployment/test/docker-compose-cypress.yml up \
           --abort-on-container-exit --exit-code-from cypress
