name: push-database-image
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build, push, and deploy
    env:
      REPO_NAME: activity
      IMAGE_NAME: activitydb
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      # - name: Update SHA
      #   run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/site/_meta

      - name: Build container image
        run: |
          docker image build \
          -f ./deployment/prod/Dockerfile.prod.database \
          -t registry.digitalocean.com/imagerepo/$(echo $REPO_NAME):$(echo $IMAGE_NAME) .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600 --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # - name: Push image to DigitalOcean Container Registry
      #   run: docker push registry.digitalocean.com/imagerepo/$(echo $REPO_NAME):$(echo $IMAGE_NAME)-$(echo $GITHUB_SHA | head -c7)

      - name: Push latest image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/imagerepo/$(echo $REPO_NAME):$(echo $IMAGE_NAME)
